import type { MarketRecord, QuoteOutcome, CallRecord } from "./types";

// Default saved profile seeded into the DB on first run. Uses clearly fake test data —
// replace with your own applicant details locally (never commit real PII).
export const defaultProfile = {
  first_name: "Test",
  last_name: "Driver",
  email: "test@example.com",
  phone: "416-555-0101",
  phone_type: "Mobile",
  date_of_birth: "1985-05-10",
  sex: "M",
  marital_status: "S",
  privacy_consent: "Yes",
  marketing_consent: "No",
  street_address: "123 Example St",
  unit: "",
  city: "Toronto",
  province: "Ontario",
  postal_code: "M5V 2T6",
  tenure: "Renting",
  vin: "1HGCM82633A004352",
  vehicle_year: "2019",
  vehicle_make: "HONDA",
  vehicle_model: "ACCORD EX 4DR",
  trim: "EX",
  drive_type: "FWD",
  fuel_type: "Gas",
  owned_leased: "Owned",
  only_registered_owner: "Yes",
  ownership_within_30_days: "No",
  purchase_price: "",
  purchase_condition: "Used",
  purchase_month: "June",
  purchase_year: "2019",
  annual_km: "12000",
  commute_days: "5",
  commute_oneway_km: "10",
  business_use: "No",
  winter_tires: "Yes",
  anti_theft: "Yes",
  parking: "Home Driveway",
  adas_features: "None",
  licence_class: "G",
  age_first_licensed: "18",
  first_licence_month: "June",
  first_licence_year: "2003",
  held_other_classes: "Yes",
  g2_month: "June",
  g2_year: "2002",
  g_within_12_months: "No",
  years_with_insurer: "3–5 years",
  prior_insurance: "More than 3 years",
  combined_policy: "No",
  telus_health: "No",
  convictions: "None",
  major_violations: "No",
  accidents: "None",
  license_suspended: "No",
  other_household_drivers: "No",
  retired: "No",
  coverage_start_date: "2026-09-01",
  liability: "$2,000,000",
  coverage_type: "All perils",
  deductible: "$1,000",
  cancellation_nonpayment: "No",
};

// Dummy test profile (same shape as defaultProfile) — for testing the aggregator
// without using the real person's details. Clearly not a real applicant.
export const fakeProfile = {
  first_name: "Test",
  last_name: "Driver",
  email: "test@example.com",
  phone: "416-555-0101",
  phone_type: "Mobile",
  date_of_birth: "1985-05-10",
  sex: "M",
  marital_status: "S",
  privacy_consent: "Yes",
  marketing_consent: "No",
  street_address: "123 Example St",
  unit: "",
  city: "Toronto",
  province: "Ontario",
  postal_code: "M5V 2T6",
  tenure: "Renting",
  vin: "1HGCM82633A004352",
  vehicle_year: "2019",
  vehicle_make: "HONDA",
  vehicle_model: "ACCORD EX 4DR",
  trim: "EX",
  drive_type: "4WD",
  fuel_type: "Gas",
  owned_leased: "Owned",
  only_registered_owner: "Yes",
  ownership_within_30_days: "No",
  purchase_price: "",
  purchase_condition: "Used",
  purchase_month: "January",
  purchase_year: "2019",
  annual_km: "15000",
  commute_days: "5",
  commute_oneway_km: "15",
  business_use: "No",
  winter_tires: "Yes",
  anti_theft: "Yes",
  parking: "Home Driveway",
  adas_features: "None",
  licence_class: "G",
  age_first_licensed: "21",
  first_licence_month: "January",
  first_licence_year: "2005",
  held_other_classes: "Yes",
  g2_month: "January",
  g2_year: "2004",
  g_within_12_months: "No",
  years_with_insurer: "5 years or more",
  prior_insurance: "More than 3 years",
  combined_policy: "No",
  telus_health: "No",
  convictions: "None",
  major_violations: "No",
  accidents: "None",
  license_suspended: "No",
  other_household_drivers: "No",
  retired: "No",
  coverage_start_date: "2026-09-01",
  liability: "$2,000,000",
  coverage_type: "All perils",
  deductible: "$1,000",
  cancellation_nonpayment: "No",
};

export const profile = {
  person: {
    first_name: "Test",
    last_name: "Driver",
    date_of_birth: "1985/05/10",
    sex: "M",
    marital_status: "S",
    street_address: "123 Example St",
    city: "Toronto",
    province: "Ontario",
    province_code: "ON",
    postal_code: "M5V 2T6",
    residence_type: "renting",
    monthly_rent: 1500,
  },
  auto: {
    make: "HONDA",
    model: "ACCORD EX 4DR",
    year: 2019,
    vin: "1HGCM82633A004352",
    owned: true,
    usage: "personal",
    annual_km: 12000,
    commute_days: 5,
    commute_km: 10,
    winter_tires: true,
    anti_theft: true,
  },
  current_insurance: {
    insurer: "Example Broker",
    policy: "TEST-POLICY-001",
    via: "Sample Brokerage Inc.",
    status: "active",
  },
};

// Seeded subset of the brief's Appendix A (32 groups / 60 legal entities). Only a
// sample is shown here for the dashboard; the full registry lives in market_registry.db.
export const marketSeed: MarketRecord[] = [
  {
    registry_id: "allstate-001",
    legal_underwriter: "Allstate Insurance Company of Canada",
    insurer_group: "Allstate",
    brand_or_program: "Allstate",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "allstate",
    quote_url: "https://apps.allstate.ca/quickquote/common/landing.aspx",
    public_phone_route: "1-800-255-7828",
    requirements: ["licence", "postal_code"],
    automation_notes: "Direct online quote (apps.allstate.ca). Gated on server/datacenter IPs; blocked.",
    status: "blocked",
    last_verified_at: "2026-08-12",
  },
  {
    registry_id: "aviva-001",
    legal_underwriter: "S&Y Insurance Company",
    insurer_group: "Aviva",
    brand_or_program: "Aviva Direct",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "aviva",
    quote_url: "https://www.aviva.ca/en/direct/",
    public_phone_route: "1-855-788-9090",
    licensed_intermediary: "Aviva Agency Services Inc. (Aviva Direct)",
    requirements: ["licence", "postal_code"],
    automation_notes: "Ontario direct quotes underwritten by S&Y Insurance Company (Aviva group), distributed by Aviva Agency Services Inc.",
    status: "quoted_comparable",
    last_verified_at: "2026-08-12",
  },
  {
    registry_id: "intact-belair-001",
    legal_underwriter: "Belair Insurance Company Inc.",
    insurer_group: "Intact",
    brand_or_program: "belairdirect",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "intact",
    quote_url: "https://www.belairdirect.com/",
    public_phone_route: "1-833-332-7852",
    licensed_intermediary: "belairdirect Agency Inc.",
    requirements: ["licence", "postal_code", "vin_optional"],
    automation_notes: "belairdirect (belairdirect Agency Inc.) distributes; underwriting by Belair Insurance Company Inc. (Intact group).",
    status: "quoted_comparable",
    last_verified_at: "2026-08-12",
  },
  {
    registry_id: "coachman-001",
    legal_underwriter: "Coachman Insurance Company",
    insurer_group: "SGI",
    brand_or_program: "Coachman",
    distribution_type: "broker",
    product_scope: "nonstandard_PPA",
    distinct_rate_source_id: "sgi-coachman",
    licensed_intermediary: "NFP Canada Corp",
    public_phone_route: "broker route",
    // Phone-only route: Coachman quotes via its broker line, not browser automation.
    phone: "+14162553417",
    status: "callback_required",
  },
  {
    registry_id: "fa-001",
    legal_underwriter: "Facility Association",
    insurer_group: "FA",
    brand_or_program: "Facility Association",
    distribution_type: "residual",
    product_scope: "nonstandard_PPA",
    distinct_rate_source_id: "fa",
    licensed_intermediary: "licensed broker required",
    status: "unresolved",
  },
];

export const quoteOutcomes: QuoteOutcome[] = [
  {
    registry_id: "intact-belair-001",
    brand: "belairdirect",
    status: "quoted_comparable",
    annual_premium: 863.04,
    monthly_premium: 71.92,
    quote_id: "BA13933019",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, $1,000 deductibles, OPCF 44R, no telematics",
    confidence: "high",
    timestamp: "2026-08-09T14:30:00-04:00",
    source: "automated",
    evidence: "evidence/belairdirect_offer_BA13933019.png",
  },
  {
    registry_id: "aviva-001",
    brand: "Aviva Direct",
    status: "quoted_non_comparable",
    annual_premium: 1104.6,
    monthly_premium: 92.05,
    quote_id: "AV-8821",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, $1,000 deductibles, OPCF 44R — different comprehensive deductible",
    confidence: "medium",
    timestamp: "2026-08-09T14:45:00-04:00",
    source: "phone",
    recording: "recordings/aviva-8821.mp3",
  },
  {
    registry_id: "coachman-001",
    brand: "Coachman (via NFP)",
    status: "quoted_non_comparable",
    annual_premium: 1320.0,
    monthly_premium: 110.0,
    quote_id: "NFP-4492",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, standard AB — non-standard rating, binder expired",
    confidence: "medium",
    timestamp: "2026-08-09T15:10:00-04:00",
    source: "phone",
    recording: "recordings/call-001.wav",
  },
];

export const callRecords: CallRecord[] = [
  {
    id: "call-001",
    registry_id: "coachman-001",
    brand: "Coachman (via NFP)",
    direction: "outbound",
    status: "quoted_non_comparable",
    recording_path: "recordings/call-001.wav",
    outcome_notes: "Broker returned premium $110.00/mo via licensed representative.",
    timestamp: "2026-08-09T15:00:00-04:00",
  },
  {
    id: "call-002",
    registry_id: "aviva-001",
    brand: "Aviva Direct",
    direction: "outbound",
    status: "quoted_non_comparable",
    recording_path: "recordings/aviva-8821.mp3",
    outcome_notes: "Returned premium $92.05/mo; comprehensive deductible differs from benchmark.",
    timestamp: "2026-08-09T14:45:00-04:00",
  },
];
