import type { MarketRecord, QuoteOutcome, CallRecord } from "./types";

// Pre-filled values shown in the intake form (Corey Barron's confirmed profile).
export const defaultProfile = {
  first_name: "Corey",
  last_name: "Barron",
  email: "cormbar@msn.com",
  phone: "519-476-0578",
  date_of_birth: "1984-10-14",
  sex: "M",
  marital_status: "S",
  street_address: "10 Tecumseh Cres",
  unit: "",
  city: "Kitchener",
  province: "Ontario",
  postal_code: "N2B 2T4",
  tenure: "Renting",
  vin: "1C6RD7GT9CS103678",
  vehicle_year: "2012",
  vehicle_make: "RAM",
  vehicle_model: "1500 Big Horn",
  trim: "Quad Cab 4WD",
  drive_type: "4WD",
  fuel_type: "Gas",
  owned_leased: "Owned",
  purchase_condition: "Used",
  purchase_month: "January",
  purchase_year: "2019",
  annual_km: "15000",
  commute_days: "5",
  commute_oneway_km: "15",
  business_use: "No",
  winter_tires: "Yes",
  anti_theft: "Yes",
  licence_class: "G",
  first_licence_year: "2005",
  held_other_classes: "Yes",
  years_with_insurer: "5 years or more",
  prior_insurance: "More than 3 years",
  convictions: "None",
  accidents: "None",
  retired: "No",
  coverage_start_date: "2026-09-01",
  liability: "$2,000,000",
  coverage_type: "All perils",
  deductible: "$1,000",
  cancellation_nonpayment: "No",
};

export const profile = {
  person: {
    first_name: "Corey",
    last_name: "Barron",
    date_of_birth: "1984/10/14",
    sex: "M",
    marital_status: "S",
    street_address: "10 Tecumseh Cres",
    city: "Kitchener",
    province: "Ontario",
    province_code: "ON",
    postal_code: "N2B 2T4",
    residence_type: "renting",
    monthly_rent: 1700,
  },
  auto: {
    make: "RAM",
    model: "1500 Big Horn Quad Cab 4WD",
    year: 2012,
    vin: "1C6RD7GT9CS103678",
    owned: true,
    usage: "personal",
    annual_km: 15000,
    commute_days: 5,
    commute_km: 15,
    winter_tires: true,
    anti_theft: true,
  },
  current_insurance: {
    insurer: "Coachman (SGI group)",
    policy: "BINDER-BARRONCO01",
    via: "NFP Canada Corp",
    status: "expired 30-day binder",
  },
};

// Seeded subset of the brief's Appendix A (32 groups / 60 legal entities). Only a
// sample is shown here for the dashboard; the full registry lives in market_registry.db.
export const marketSeed: MarketRecord[] = [
  {
    registry_id: "allstate-001",
    legal_underwriter: "Allstate Insurance Company of Canada",
    insurer_group: "Allstate",
    brand_or_program: "Allstate",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "allstate",
    quote_url: "https://www.allstate.ca",
    status: "unresolved",
  },
  {
    registry_id: "aviva-001",
    legal_underwriter: "Aviva Insurance Company of Canada",
    insurer_group: "Aviva",
    brand_or_program: "Aviva Direct",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "aviva",
    quote_url: "https://www.aviva.ca",
    status: "quoted_comparable",
  },
  {
    registry_id: "intact-belair-001",
    legal_underwriter: "Belair Insurance Company Inc.",
    insurer_group: "Intact",
    brand_or_program: "belairdirect",
    distribution_type: "direct",
    product_scope: "standard_PPA",
    distinct_rate_source_id: "intact",
    quote_url: "https://www.belairdirect.com",
    status: "quoted_comparable",
    automation_notes: "quote #BA13933019, $71.92/mo, 2026-08-09",
  },
  {
    registry_id: "coachman-001",
    legal_underwriter: "Coachman Insurance Company",
    insurer_group: "SGI",
    brand_or_program: "Coachman",
    distribution_type: "broker",
    product_scope: "nonstandard_PPA",
    distinct_rate_source_id: "sgi-coachman",
    licensed_intermediary: "NFP Canada Corp",
    public_phone_route: "broker route",
    // Phone-only route: Coachman quotes via its broker line, not browser automation.
    phone: "+14162553417",
    status: "callback_required",
  },
  {
    registry_id: "fa-001",
    legal_underwriter: "Facility Association",
    insurer_group: "FA",
    brand_or_program: "Facility Association",
    distribution_type: "residual",
    product_scope: "nonstandard_PPA",
    distinct_rate_source_id: "fa",
    licensed_intermediary: "licensed broker required",
    status: "unresolved",
  },
];

export const quoteOutcomes: QuoteOutcome[] = [
  {
    registry_id: "intact-belair-001",
    brand: "belairdirect",
    status: "quoted_comparable",
    annual_premium: 863.04,
    monthly_premium: 71.92,
    quote_id: "BA13933019",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, $1,000 deductibles, OPCF 44R, no telematics",
    confidence: "high",
    timestamp: "2026-08-09T14:30:00-04:00",
    source: "automated",
    evidence: "evidence/belairdirect_offer_BA13933019.png",
  },
  {
    registry_id: "aviva-001",
    brand: "Aviva Direct",
    status: "quoted_non_comparable",
    annual_premium: 1104.6,
    monthly_premium: 92.05,
    quote_id: "AV-8821",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, $1,000 deductibles, OPCF 44R — different comprehensive deductible",
    confidence: "medium",
    timestamp: "2026-08-09T14:45:00-04:00",
    source: "phone",
    recording: "recordings/aviva-8821.mp3",
  },
  {
    registry_id: "coachman-001",
    brand: "Coachman (via NFP)",
    status: "quoted_non_comparable",
    annual_premium: 1320.0,
    monthly_premium: 110.0,
    quote_id: "NFP-4492",
    effective_date: "2026-08-09",
    coverage_notes: "$2M TPL, DCPD incl, standard AB — non-standard rating, binder expired",
    confidence: "medium",
    timestamp: "2026-08-09T15:10:00-04:00",
    source: "phone",
    recording: "recordings/call-001.wav",
  },
];

export const callRecords: CallRecord[] = [
  {
    id: "call-001",
    registry_id: "coachman-001",
    brand: "Coachman (via NFP)",
    direction: "outbound",
    status: "quoted_non_comparable",
    recording_path: "recordings/call-001.wav",
    outcome_notes: "Broker returned premium $110.00/mo via licensed representative.",
    timestamp: "2026-08-09T15:00:00-04:00",
  },
  {
    id: "call-002",
    registry_id: "aviva-001",
    brand: "Aviva Direct",
    direction: "outbound",
    status: "quoted_non_comparable",
    recording_path: "recordings/aviva-8821.mp3",
    outcome_notes: "Returned premium $92.05/mo; comprehensive deductible differs from benchmark.",
    timestamp: "2026-08-09T14:45:00-04:00",
  },
];
